# Generated by Django 2.2.3 on 2019-08-01 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20190731_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asign',
            old_name='spot',
            new_name='slot',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='spot',
            new_name='slot',
        ),
    ]
